# image based on fluentd v1.14-1
FROM fluent/fluentd:v1.15-debian-armhf-1
# Use root account to use apk
USER root

# below RUN includes plugin as examples elasticsearch is not required# you may customize including plugins as you wish
RUN buildDeps="sudo make gcc g++ libc-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
        && gem uninstall -I elasticsearch \
        && gem install elasticsearch -v 7.17.0 \
        && sudo gem install fluent-plugin-elasticsearch \
        && sudo gem sources --clear-all \
        && apk del .build-deps \
        && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

# copy fluentd configuration from host image
# COPY ./conf/fluent.conf /fluentd/etc/
# # copy binary start file
# COPY entrypoint.sh /bin/

# RUN chmod +x /bin/entrypoint.sh

# USER fluent